# This workflow will upload a Python Package to Test PyPI when a release is created

name: Upload Python Package to Test PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest  # Use Ubuntu for a robust CI environment

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build release distributions
        run: |
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  testpypi-publish:
    runs-on: ubuntu-latest  # Use Ubuntu for consistency

    needs:
      - release-build
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    environment:
      name: testpypi
      url: https://test.pypi.org/project/pyfitsserver  # Replace YOURPROJECTNAME with your actual project name

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          repository-url: https://test.pypi.org/legacy/

  realpypi-publish:
    runs-on: ubuntu-latest  # Use Ubuntu for consistency

    needs:
      - release-build

    if: false  # Disable this job for now

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/project/pyfitsserver  # Replace YOURPROJECTNAME with your actual project name

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          repository-url: https://upload.pypi.org/legacy/